import React from "react";
import './key.css';
import { Synth } from "tone";
import * as Tone from 'tone';



const Key = ({note, type}) => {
    const keyType = type === "white" ? "whiteKey" : "blackKey";
    // const synth = new Synth();
    // synth.toDestination();
    // let samplerObject = {
    //     "A0": "A0.mp3",
    //     "A#0": "As0.mp3",
    //     "B0": "../../../piano-samples/0-b.wav",

    //     "C1":"../../../piano-samples/1-a.wav",
    //     "C#1":"../../../piano-samples/1-as.wav",
    //     "D1":"../../../piano-samples/1-b.wav",
    //     "D#1":"../../../piano-samples/1-c.wav",
    //     "E1":"../../../piano-samples/1-cs.wav",
    //     "F1":"../../../piano-samples/1-d.wav",
    //     "F#1":"../../../piano-samples/1-ds.wav",
    //     "G1":"../../../piano-samples/1-e.wav",
    //     "G#1":"../../../piano-samples/1-f.wav",
    //     "A1":"../../../piano-samples/1-fs.wav",
    //     "A#1":"../../../piano-samples/1-g.wav",
    //     "B1":"../../../piano-samples/1-gs.wav",

    //     "C2":"../../../piano-samples/2-a.wav",
    //     "C#2":"../../../piano-samples/2-as.wav",
    //     "D2":"../../../piano-samples/2-b.wav",
    //     "D#2":"../../../piano-samples/2-c.wav",
    //     "E2":"../../../piano-samples/2-cs.wav",
    //     "F2":"../../../piano-samples/2-d.wav",
    //     "F#2":"../../../piano-samples/2-ds.wav",
    //     "G2":"../../../piano-samples/2-e.wav",
    //     "G#2":"../../../piano-samples/2-f.wav",
    //     "A2":"../../../piano-samples/2-fs.wav",
    //     "A#2":"../../../piano-samples/2-g.wav",
    //     "B2":"../../../piano-samples/2-gs.wav",

    //     "C3":"../../../piano-samples/3-a.wav",
    //     "C#3":"../../../piano-samples/3-as.wav",
    //     "D3":"../../../piano-samples/3-b.wav",
    //     "D#3":"../../../piano-samples/3-c.wav",
    //     "E3":"../../../piano-samples/3-cs.wav",
    //     "F3":"../../../piano-samples/3-d.wav",
    //     "F#3":"../../../piano-samples/3-ds.wav",
    //     "G3":"../../../piano-samples/3-e.wav",
    //     "G#3":"../../../piano-samples/3-f.wav",
    //     "A3":"../../../piano-samples/3-fs.wav",
    //     "A#3":"../../../piano-samples/3-g.wav",
    //     "B3":"../../../piano-samples/3-gs.wav",

    //     "C4":"../../../piano-samples/4-a.wav",
    //     "C#4":"../../../piano-samples/4-as.wav",
    //     "D4":"../../../piano-samples/4-b.wav",
    //     "D#4":"../../../piano-samples/4-c.wav",
    //     "E4":"../../../piano-samples/4-cs.wav",
    //     "F4":"../../../piano-samples/4-d.wav",
    //     "F#4":"../../../piano-samples/4-ds.wav",
    //     "G4":"../../../piano-samples/4-e.wav",
    //     "G#4":"../../../piano-samples/4-f.wav",
    //     "A4":"../../../piano-samples/4-fs.wav",
    //     "A#4":"../../../piano-samples/4-g.wav",
    //     "B4":"../../../piano-samples/4-gs.wav",
        
    //     "C5":"../../../piano-samples/5-a.wav",
    //     "C#5":"../../../piano-samples/5-as.wav",
    //     "D5":"../../../piano-samples/5-b.wav",
    //     "D#5":"../../../piano-samples/5-c.wav",
    //     "E5":"../../../piano-samples/5-cs.wav",
    //     "F5":"../../../piano-samples/5-d.wav",
    //     "F#5":"../../../piano-samples/5-ds.wav",
    //     "G5":"../../../piano-samples/5-e.wav",
    //     "G#5":"../../../piano-samples/5-f.wav",
    //     "A5":"../../../piano-samples/5-fs.wav",
    //     "A#5":"../../../piano-samples/5-g.wav",
    //     "B5":"../../../piano-samples/5-gs.wav",
        
    //     "C6":"../../../piano-samples/6-a.wav",
    //     "C#6":"../../../piano-samples/6-as.wav",
    //     "D6":"../../../piano-samples/6-b.wav",
    //     "D#6":"../../../piano-samples/6-c.wav",
    //     "E6":"../../../piano-samples/6-cs.wav",
    //     "F6":"../../../piano-samples/6-d.wav",
    //     "F#6":"../../../piano-samples/6-ds.wav",
    //     "G6":"../../../piano-samples/6-e.wav",
    //     "G#6":"../../../piano-samples/6-f.wav",
    //     "A6":"../../../piano-samples/6-fs.wav",
    //     "A#6":"../../../piano-samples/6-g.wav",
    //     "B6":"../../../piano-samples/6-gs.wav",
        
    //     "C7":"../../../piano-samples/7-a.wav",
    //     "C#7":"../../../piano-samples/7-as.wav",
    //     "D7":"../../../piano-samples/7-b.wav",
    //     "D#7":"../../../piano-samples/7-c.wav",
    //     "E7":"../../../piano-samples/7-cs.wav",
    //     "F7":"../../../piano-samples/7-d.wav",
    //     "F#7":"../../../piano-samples/7-ds.wav",
    //     "G7":"../../../piano-samples/7-e.wav",
    //     "G#7":"../../../piano-samples/7-f.wav",
    //     "A7":"../../../piano-samples/7-fs.wav",
    //     "A#7":"../../../piano-samples/7-g.wav",
    //     "B7":"../../../piano-samples/7-gs.wav",

    //     "C8": "../../../piano-samples/8-c.wav",
    // };

//    let samplerObject = {
//         'A0': 'A0.mp3',
//         'A#0': 'As0.mp3',
//         'B0': 'B0.mp3',
//         'C1': 'C1.mp3',
//         'C#1': 'Cs1.mp3',
//         'D1': 'D1.mp3',
//         'D#1': 'Ds1.mp3',
//         'E1': 'E1.mp3',
//         'F1': 'F1.mp3',
//         'F#1': 'Fs1.mp3',
//         'G1': 'G1.mp3',
//         'G#1': 'Gs1.mp3',
//         'A1': 'A1.mp3',
//         'A#1': 'As1.mp3',
//         'B1': 'B1.mp3',
//         'C2': 'C2.mp3',
//         'C#2': 'Cs2.mp3',
//         'D2': 'D2.mp3',
//         'D#2': 'Ds2.mp3',
//         'E2': 'E2.mp3',
//         'F2': 'F2.mp3',
//         'F#2': 'Fs2.mp3',
//         'G2': 'G2.mp3',
//         'G#2': 'Gs2.mp3',
//         'A2': 'A2.mp3',
//         'A#2': 'As2.mp3',
//         'B2': 'B2.mp3',
//         'C3': 'C3.mp3',
//         'C#3': 'Cs3.mp3',
//         'D3': 'D3.mp3',
//         'D#3': 'Ds3.mp3',
//         'E3': 'E3.mp3',
//         'F3': 'F3.mp3',
//         'F#3': 'Fs3.mp3',
//         'G3': 'G3.mp3',
//         'G#3': 'Gs3.mp3',
//         'A3': 'A3.mp3',
//         'A#3': 'As3.mp3',
//         'B3': 'B3.mp3',
//         'C4': 'C4.mp3',
//         'C#4': 'Cs4.mp3',
//         'D4': 'D4.mp3',
//         'D#4': 'Ds4.mp3',
//         'E4': 'E4.mp3',
//         'F4': 'F4.mp3',
//         'F#4': 'Fs4.mp3',
//         'G4': 'G4.mp3',
//         'G#4': 'Gs4.mp3',
//         'A4': 'A4.mp3',
//         'A#4': 'As4.mp3',
//         'B4': 'B4.mp3',
//         'C5': 'C5.mp3',
//         'C#5': 'Cs5.mp3',
//         'D5': 'D5.mp3',
//         'D#5': 'Ds5.mp3',
//         'E5': 'E5.mp3',
//         'F5': 'F5.mp3',
//         'F#5': 'Fs5.mp3',
//         'G5': 'G5.mp3',
//         'G#5': 'Gs5.mp3',
//         'A5': 'A5.mp3',
//         'A#5': 'As5.mp3',
//         'B5': 'B5.mp3',
//         'C6': 'C6.mp3',
//         'C#6': 'Cs6.mp3',
//         'D6': 'D6.mp3',
//         'D#6': 'Ds6.mp3',
//         'E6': 'E6.mp3',
//         'F6': 'F6.mp3',
//         'F#6': 'Fs6.mp3',
//         'G6': 'G6.mp3',
//         'G#6': 'Gs6.mp3',
//         'A6': 'A6.mp3',
//         'A#6': 'As6.mp3',
//         'B6': 'B6.mp3',
//         'C7': 'C7.mp3',
//         'C#7': 'Cs7.mp3',
//         'D7': 'D7.mp3',
//         'D#7': 'Ds7.mp3',
//         'E7': 'E7.mp3',
//         'F7': 'F7.mp3',
//         'F#7': 'Fs7.mp3',
//         'G7': 'G7.mp3',
//         'G#7': 'Gs7.mp3',
//         'A7': 'A7.mp3',
//         'A#7': 'As7.mp3',
//         'B7': 'B7.mp3',
//         'C8': 'C8.mp3'
//       };

    const sampler = new Tone.Sampler({
        urls: {
            "C6": "C6.mp3",
            "D#6": "Ds6.mp3",
            "F#6": "Fs6.mp3",
            "A6": "A6.mp3",
        },
        release: 1,
        baseUrl: "https://tonejs.github.io/audio/salamander/",
    }).toDestination();
    

    const handleKeyPress = () => {
        
        Tone.loaded().then(() => {
            sampler.triggerAttackRelease(note, 8);
        });
    }
    return (
        <button onMouseDown={handleKeyPress} data-note-name={`${note}`} className={`key ${keyType}`}>{note}</button>
    );
};

export default Key;